version: "3"
services:
  hub:
    container_name: hub
    image: seleniarm/hub:4.10
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: 1g
    depends_on:
    - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: 1g
    depends_on:
    - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2