version: "3"
services:
  selenium_hub:
    container_name: selenium_hub
    image: seleniarm/hub:4.10
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: 2g
    depends_on:
    - selenium_hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: 2g
    depends_on:
    - selenium_hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1