version: "3"
services:
  vendor-portal:
    image: mdmsn/tea-selenium
    environment:
    - BROWSER
    - HUB_HOST=hub    
    - THREAD_COUNT=3
    - TEST_SUITE=user-login.xml
    - UI_URL
    volumes:
    - ./output/user-login:/home/tea-app-tests/test-output