version: "3"
services:
  user-login:
    image: mdmsn/tea-selenium:latest
    environment:
    - BROWSER
    - HUB_HOST=selenium_hub
    - THREAD_COUNT=2
    - TEST_SUITE=user-login.xml
    - UI_URL
    volumes:
    - ./output/user-login:/home/tea-app-tests/test-output