version: "3"
services:
  user-login:
    image: mdmsn/tea-selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub    
    - THREAD_COUNT=3
    - TEST_SUITE=user-login.xml
    - UI_URL
    volumes:
    - ./output/user-login:/home/tea-app-tests/test-output